/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrbRouteImport } from './routes/orb'
import { Route as ApiPublicMcpActivityRouteImport } from './routes/api/public/mcp-activity'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrbRoute = OrbRouteImport.update({
  id: '/orb',
  path: '/orb',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMcpActivityRoute = ApiPublicMcpActivityRouteImport.update({
  id: '/api/public/mcp-activity',
  path: '/api/public/mcp-activity',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/orb': typeof OrbRoute
  '/api/public/mcp-activity': typeof ApiPublicMcpActivityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/orb': typeof OrbRoute
  '/api/public/mcp-activity': typeof ApiPublicMcpActivityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/orb': typeof OrbRoute
  '/api/public/mcp-activity': typeof ApiPublicMcpActivityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/orb' | '/api/public/mcp-activity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/orb' | '/api/public/mcp-activity'
  id: '__root__' | '/' | '/orb' | '/api/public/mcp-activity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrbRoute: typeof OrbRoute
  ApiPublicMcpActivityRoute: typeof ApiPublicMcpActivityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orb': {
      id: '/orb'
      path: '/orb'
      fullPath: '/orb'
      preLoaderRoute: typeof OrbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp-activity': {
      id: '/api/public/mcp-activity'
      path: '/api/public/mcp-activity'
      fullPath: '/api/public/mcp-activity'
      preLoaderRoute: typeof ApiPublicMcpActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrbRoute: OrbRoute,
  ApiPublicMcpActivityRoute: ApiPublicMcpActivityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
